Explorer to Templates linking
When clicking on a template link in the explorer tab, the resulting page
would be an unreadable error trace with `TypeError: t is not a function`

This is caused by the search terms being incorrectly defined for this
page.